### ISSUE TITLE
Missing reading response link on "Error Messages in Python"

### ISSUE THREAD

**Issue by LucaOnline** [zaneveld/full_spectrum_bioinformatics#81]
There is no reading response link at the bottom of [content/04_exploring_python/error_messages_in_python.ipynb](https://github.com/zaneveld/full_spectrum_bioinformatics/blob/master/content/04_exploring_python/error_messages_in_python.ipynb). Additionally, on the reading response form, there is no entry for this reading.

**Comment by zaneveld** [comment]
Thanks for raising the issue Luca — this is now be resolved.
